server:
  port: 8099

spring:
  mail:
    host: smtp.qq.com
    username: xxxxxx@qq.com
    password: 授权码
    properties:
      mail:
        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable :true
    default-encoding: utf-8

