server:
  port: 8099

spring:
  mail:
    host: smtp.qq.com
    username: 1111111@qq.com
    password: xxxxxxxxxxx  #自己到QQ官网获取
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

