server:
  port: 8089
spring:
  thymeleaf:
    cache: false  #将缓存关闭，不然我们改变页面之后可能看不到更改的内容，默认是打开true的
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
